#define WAYGATE_VERSION_MAJOR @WAYGATE_VERSION_MAJOR@
#define WAYGATE_VERSION_MINOR @WAYGATE_VERSION_MINOR@
#define PROJECT_CONFIG_DIR @PROJECT_CONFIG_DIR@

#include "reader.hpp"
#include "signals.hpp"